// Generated by gencpp from file communication_tutorials/SumIntsRequest.msg
// DO NOT EDIT!


#ifndef COMMUNICATION_TUTORIALS_MESSAGE_SUMINTSREQUEST_H
#define COMMUNICATION_TUTORIALS_MESSAGE_SUMINTSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace communication_tutorials
{
template <class ContainerAllocator>
struct SumIntsRequest_
{
  typedef SumIntsRequest_<ContainerAllocator> Type;

  SumIntsRequest_()
    : a(0)
    , i(0)  {
    }
  SumIntsRequest_(const ContainerAllocator& _alloc)
    : a(0)
    , i(0)  {
  (void)_alloc;
    }



   typedef int64_t _a_type;
  _a_type a;

   typedef int64_t _i_type;
  _i_type i;





  typedef boost::shared_ptr< ::communication_tutorials::SumIntsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::communication_tutorials::SumIntsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SumIntsRequest_

typedef ::communication_tutorials::SumIntsRequest_<std::allocator<void> > SumIntsRequest;

typedef boost::shared_ptr< ::communication_tutorials::SumIntsRequest > SumIntsRequestPtr;
typedef boost::shared_ptr< ::communication_tutorials::SumIntsRequest const> SumIntsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::communication_tutorials::SumIntsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::communication_tutorials::SumIntsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace communication_tutorials

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::communication_tutorials::SumIntsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::communication_tutorials::SumIntsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::communication_tutorials::SumIntsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::communication_tutorials::SumIntsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::communication_tutorials::SumIntsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::communication_tutorials::SumIntsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::communication_tutorials::SumIntsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7882d8ba6efc5d8e0a006d2f1230e9fa";
  }

  static const char* value(const ::communication_tutorials::SumIntsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7882d8ba6efc5d8eULL;
  static const uint64_t static_value2 = 0x0a006d2f1230e9faULL;
};

template<class ContainerAllocator>
struct DataType< ::communication_tutorials::SumIntsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "communication_tutorials/SumIntsRequest";
  }

  static const char* value(const ::communication_tutorials::SumIntsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::communication_tutorials::SumIntsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 a\n\
int64 i\n\
";
  }

  static const char* value(const ::communication_tutorials::SumIntsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::communication_tutorials::SumIntsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
      stream.next(m.i);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SumIntsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::communication_tutorials::SumIntsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::communication_tutorials::SumIntsRequest_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<int64_t>::stream(s, indent + "  ", v.a);
    s << indent << "i: ";
    Printer<int64_t>::stream(s, indent + "  ", v.i);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMUNICATION_TUTORIALS_MESSAGE_SUMINTSREQUEST_H
