// Generated by gencpp from file communication_tutorials/SumInts.msg
// DO NOT EDIT!


#ifndef COMMUNICATION_TUTORIALS_MESSAGE_SUMINTS_H
#define COMMUNICATION_TUTORIALS_MESSAGE_SUMINTS_H

#include <ros/service_traits.h>


#include <communication_tutorials/SumIntsRequest.h>
#include <communication_tutorials/SumIntsResponse.h>


namespace communication_tutorials
{

struct SumInts
{

typedef SumIntsRequest Request;
typedef SumIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SumInts
} // namespace communication_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::communication_tutorials::SumInts > {
  static const char* value()
  {
    return "c4ba0434e54f58dda95d9e73abb2a1f5";
  }

  static const char* value(const ::communication_tutorials::SumInts&) { return value(); }
};

template<>
struct DataType< ::communication_tutorials::SumInts > {
  static const char* value()
  {
    return "communication_tutorials/SumInts";
  }

  static const char* value(const ::communication_tutorials::SumInts&) { return value(); }
};


// service_traits::MD5Sum< ::communication_tutorials::SumIntsRequest> should match 
// service_traits::MD5Sum< ::communication_tutorials::SumInts > 
template<>
struct MD5Sum< ::communication_tutorials::SumIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::communication_tutorials::SumInts >::value();
  }
  static const char* value(const ::communication_tutorials::SumIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::communication_tutorials::SumIntsRequest> should match 
// service_traits::DataType< ::communication_tutorials::SumInts > 
template<>
struct DataType< ::communication_tutorials::SumIntsRequest>
{
  static const char* value()
  {
    return DataType< ::communication_tutorials::SumInts >::value();
  }
  static const char* value(const ::communication_tutorials::SumIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::communication_tutorials::SumIntsResponse> should match 
// service_traits::MD5Sum< ::communication_tutorials::SumInts > 
template<>
struct MD5Sum< ::communication_tutorials::SumIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::communication_tutorials::SumInts >::value();
  }
  static const char* value(const ::communication_tutorials::SumIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::communication_tutorials::SumIntsResponse> should match 
// service_traits::DataType< ::communication_tutorials::SumInts > 
template<>
struct DataType< ::communication_tutorials::SumIntsResponse>
{
  static const char* value()
  {
    return DataType< ::communication_tutorials::SumInts >::value();
  }
  static const char* value(const ::communication_tutorials::SumIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COMMUNICATION_TUTORIALS_MESSAGE_SUMINTS_H
